server:
  port: 1003

spring:
  application:
    name: Consumer
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc: #静态资源处理
    static-path-pattern: /static/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
  instance:
    prefer-ip-address: true

feign: #断路由
  hystrix:
    enabled: true
